Remove unwanted characters from poll info
Similar to PR 3883.

Removing carriage return character \r, causing the following error while trying view minigraphs on device list page:

SyntaxError: unterminated string literal

return overlib('<div style=\'background-color: #FFFFFF;\'><div><span class=
This issue has been experienced with S4810 devices.